[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mujoco_simulator_cpp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_BUILD_TYPE=RelWithDebInfo",
  "-S",
  ".",
  ".build/",
] }
build = { cmd = "cmake --build .build/", depends_on = ["configure"] }

[dependencies]

ninja = ">=1.12.1,<2"
cmake = ">=3.30.5,<4"
lld = ">=19.1.2,<20"
rust = ">=1.81.0,<2"
glfw = ">=3.4,<4"
cpp-expected = ">=1.1.0,<2"
spdlog = ">=1.14.1,<2"
fmt = ">=11.0.2,<12"
range-v3 = ">=0.12.0,<0.13"
nlohmann_json = ">=3.11.3,<4"

[feature.lint.dependencies]
pre-commit = "*"
prettier = "*"
taplo = "*"

[feature.lint.tasks]
lint = "pre-commit run --all-files"

[environments]
lint = { features = ["lint"], no-default-feature = true }
