[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mujoco_zenoh"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

configure-zenoh-cpp = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
  "-DCMAKE_BUILD_TYPE=Release",
  "-S",
  "../external/zenoh-cpp",
  ".build/zenoh-cpp",
], depends_on = [
  "install-zenoh-c",
] }

configure-zenoh-c = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_BUILD_TYPE=Release",
  "-S",
  "../external/zenoh-cpp/zenoh-c",
  ".build/zenoh-c",
] }
build-zenoh-c = { cmd = [
  "cmake",
  "--build",
  ".build/zenoh-c",
], depends_on = [
  "configure-zenoh-c",
] }
install-zenoh-c = { cmd = [
  "cmake",
  "--install",
  ".build/zenoh-c",
  "--prefix",
  ".pixi/envs/default",
], depends_on = [
  "build-zenoh-c",
] }
build-zenoh-cpp = { cmd = [
  "cmake",
  "--build",
  ".build/zenoh-cpp",
], depends_on = [
  "configure-zenoh-cpp",
] }
build-zenoh-cpp-examples = { cmd = [
  "cmake",
  "--build",
  ".build/zenoh-cpp",
  "--target examples",
], depends_on = [
  "build-zenoh-cpp",
] }
install-zenoh-cpp = { cmd = [
  "cmake",
  "--install",
  ".build/zenoh-cpp",
  "--prefix",
  "$CONDA_PREFIX",
], depends_on = [
  "build-zenoh-cpp",
] }
configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_BUILD_TYPE=RelWithDebInfo",
  "-S",
  ".",
  ".build/mujoco",
] }
build = { cmd = "cmake --build .build/mujoco", depends_on = ["configure"] }
# install = { cmd = "cmake --install .build/mujoco --prefix .pixi/envs/default", depends_on = ["build"] }

[dependencies]
ninja = ">=1.12.1,<2"
cmake = ">=3.30.5,<4"
lld = ">=19.1.2,<20"
rust = ">=1.81.0,<2"
glfw = ">=3.4,<4"
cpp-expected = ">=1.1.0,<2"
spdlog = ">=1.14.1,<2"
fmt = ">=11.0.2,<12"
range-v3 = ">=0.12.0,<0.13"

[feature.lint.dependencies]
pre-commit = "*"
prettier = "*"
taplo = "*"

[feature.lint.tasks]
lint = "pre-commit run --all-files"

[environments]
lint = { features = ["lint"], no-default-feature = true }
