[robot]
base_link = "world"
description = "../../external/mujoco_menagerie/kinova_gen3/scene.xml"
mappings = {}

[group.arm]
joints = [
  "joint_1",
  "joint_2",
  "joint_3",
  "joint_4",
  "joint_5",
  "joint_6",
  "joint_7",
]
tcp_link_name = "bracelet_link" # "kinova_hand_tcp"

[named_states]
home = [0.0, 0.0, -3.14, -2.51, 0.0, 0.96, 1.57]

[velocity_limits]
joint_1 = 1.0
joint_2 = 1.0
joint_3 = 1.0
joint_4 = 1.0
joint_5 = 1.0
joint_6 = 1.0
joint_7 = 1.0

[acceleration_limits]
joint_1 = 1.0
joint_2 = 1.0
joint_3 = 1.0
joint_4 = 1.0
joint_5 = 1.0
joint_6 = 1.0
joint_7 = 1.0
