[project]
authors = ["JafarAbdi <jafar.uruc@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mujoco_simulator_cpp"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

configure = { cmd = [
  "cmake",
  "-GNinja",
  "-DCMAKE_BUILD_TYPE=RelWithDebInfo",
  "-DCMAKE_C_COMPILER=clang",
  "-DCMAKE_CXX_COMPILER=clang++",
  "-DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=lld",
  "-DCMAKE_MODULE_LINKER_FLAGS=-fuse-ld=lld",
  "-DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld",
  "-S",
  ".",
  ".build/",
] }
build = { cmd = "cmake --build .build/", depends-on = ["configure"] }
install = { cmd = "cmake --install .build/ --prefix .install", depends-on = [
  "build",
] }

[dependencies]
glfw = ">=3.4,<4"
cpp-expected = ">=1.1.0,<2"
spdlog = ">=1.14.1,<2"
fmt = ">=11.0.2,<12"
range-v3 = ">=0.12.0,<0.13"

ninja = ">=1.12.1,<2"
cmake = ">=3.30.5,<4"
lld = ">=19.1.2,<20"
rust = ">=1.81.0,<2"
mesalib = ">=24.3.3,<25"
clangxx = ">=19.1.7,<20"
# For CMAKE_CXX_COMPILER_AR
llvm-tools = ">=19.1.7,<20"
mujoco_simulator_msgs = { path = "external/mujoco_simulator_msgs" }

[feature.lint.dependencies]
pre-commit = "*"
prettier = "*"
taplo = "*"

[feature.lint.tasks]
lint = "pre-commit run --all-files"

[feature.appimage.activation.env]
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:.build/_deps/mujoco-src/lib:.build/_deps/zenoh-c-src/lib"

[feature.appimage.tasks]
build-appimage = { cmd = """
(test -e linuxdeploy-x86_64.AppImage || \
wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage) && \
chmod +x linuxdeploy-x86_64.AppImage && \
./linuxdeploy-x86_64.AppImage --appdir .install/ \
                              -d resources/mujoco_simulator.desktop \
                              -i resources/mujoco_simulator.png \
                              --output appimage \
                              --library $CONDA_PREFIX/lib/libstdc++.so.6 \
                              --executable=.install/bin/mujoco_simulator
""", depends-on = [
  "install",
] }

[environments]
lint = { features = ["lint"], no-default-feature = true }
appimage = { features = ["appimage"] }
