[robot]
base_link = "world"
description = "../../external/mujoco_menagerie/universal_robots_ur5e/scene.xml"
mappings = {}

[group.arm]
joints = [
  "shoulder_pan_joint",
  "shoulder_lift_joint",
  "elbow_joint",
  "wrist_1_joint",
  "wrist_2_joint",
  "wrist_3_joint",
]
tcp_link_name = "wrist_3_link" # Add tcp link

[named_states]
home = [0.0, -1.57, 1.57, -1.57, -1.57, 0.0]

[velocity_limits]
shoulder_pan_joint = 1.0
shoulder_lift_joint = 1.0
elbow_joint = 1.0
wrist_1_joint = 1.0
wrist_2_joint = 1.0
wrist_3_joint = 1.0

[acceleration_limits]
shoulder_pan_joint = 1.0
shoulder_lift_joint = 1.0
elbow_joint = 1.0
wrist_1_joint = 1.0
wrist_2_joint = 1.0
wrist_3_joint = 1.0
