name: CI
on:
  pull_request:
  push:
    branches:
      - main

# Automatically stop old builds on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          frozen: true
          environments: lint
      - run: pixi run lint --color=always --show-diff-on-failure
  build-simulator:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install OpenGL development libraries
        run: sudo apt-get install libgl1-mesa-dev
      - uses: prefix-dev/setup-pixi@v0.8.8
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          frozen: true
      - run: pixi run build
